version: '1.0'
services:
  client:
    build: ./client
    container_name: client_side
    ports:
      - "3000:80"
  server:
    build: ./server
    container_name: server_side
    ports:
      - "5000:5000"